env:
    CIRRUS_CLONE_DEPTH: 1
    rom_name: Nusantara
    device: lavender
    TELEGRAM_ID: $tg_id
    BOT_API: $bot_api

task:
  name: "Snx-R"
  timeout_in: 240m
  container:
      image: accupara/aosp@sha256:0338cd1b766cdc873e5cf039d38bd1eaec57990681e31a0a8d618109d7a1f87e
      # image: ghcr.io/snx-r/cirrus:latest
      cpu: 8
      memory: 32G
      stateful: true
      greedy: true
      volumes:
          - /home/cirrus:/home/cirrus
          - /home/cirrus/ccache:/home/cirrus/ccache
          - /home/cirrus/.config:/home/cirrus/.config
          
  cache_script:
    - sudo apt update && sudo apt install ccache -y

  storage_script:
    - df -h .
    - free -h

  vanilla_script:
    - mkdir Arrow && cd Arrow
    - git clone https://Sa-Sajjad:$ght@github.com/Sa-Sajjad/Snx -b cirrus
    - bash Snx/build.sh --sync -gf
